#!/usr/bin/python3

import os
import sys

src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'src'))
sys.path.append(src_path)

from slackviewerfiles.main import main

if __name__ == '__main__':
    main()
